### ISSUE TITLE
Hello friend,do you know why the Fn-Key with F2,F3  can not work correctly?

### ISSUE THREAD

**Issue by zb2947244682** [bearkfear/SAMSUNG-NP300E5L-HACKINTOSH#2]
After I installed the mac os mojove completely,I try to press Fn key and F2,F3 key to adjust the brightness,but it didn't work.

Then,I opened the display panel,there was no brightness bar in the panel.

This problem puzzled me for a long time...

Haha~~~

Maybe you known this issue,so I try to ask you~~~

Thanks~

**Comment by bearkfear** [comment]
Im using a real mac today but i think that the fn key come enabled by default, you have to change the bright in f1 and f2 keys.
